{{- if and .Values.persistence.enabled .Values.persistence.encryptionKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "suse-ai-up.fullname" . }}-storage
  labels:
    {{- include "suse-ai-up.labels" . | nindent 4 }}
type: Opaque
data:
  encryption-key: {{ .Values.persistence.encryptionKey | b64enc | quote }}
{{- end }}
